workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 120
    # environment:
    #   vars:
    #     JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Set Java version
    scripts:
      - name: Clean project
        script: |
          chmod +x gradlew
          ./gradlew clean
      - name: Build APK
        script: |
          ./gradlew assembleRelease
      - name: Debug List generated files
        script: |
          echo "Checking APK directory:"
          ls -l app/build/outputs/apk/
          # ls -l build/
          # ls -l app/release/
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
