workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 120
    # environment:
    #   vars:
    #     JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Set Java version
    scripts:
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
