name: Android CI
on: 
  workflow_dispatch

jobs:
  Code-checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  # Lint-Report:
  #   needs: Code-checkout
  #   runs-on: self-hosted
  #   steps:
  #   - name: Lint Report
  #     run: ./gradlew lintDebug
  #   - name: Upload html test report
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: index.html
  #       path: app/build/reports/lint-results-debug.html
  #       if-no-files-found: warn
    
  # Sonar-Analysis:
  #   needs: Lint-Report
  #   runs-on: self-hosted
  #   steps:      
  #   - name: Sonar Analysis
  #     run: ./gradlew sonarqube

  # Unit-Test: 
  #  needs: Sonar-Analysis
  #  runs-on: self-hosted
  #  steps:    
  #   - name: Unit Test Case
  #     run: ./gradlew test
  #   - name: Upload unit test report
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: test-report.html
  #       path: app/build/reports/tests/testDebugUnitTest/index.html
  #       if-no-files-found: warn  

  # Build: 
  #  needs: Unit-Test
  #  runs-on: self-hosted
  #  steps:    
  #   - name: Build
  #     run: ./gradlew assembleDebug

  # Deploy-apk: 
  #  needs: Build
  #  runs-on: self-hosted
  #  steps:
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '16'

  #   - name: Install App Center CLI
  #     run: |
  #       npm install -g appcenter-cli

  #   - name: Upload to App Center
  #     run: appcenter distribute release --disable-telemetry --app sohampa-cybage.com/Demo_Android_App -f ./app/build/outputs/apk/debug/app-debug.apk --token cff85da442d6be30154ab06a14048f2d9e726614 -g "test"
  Slack-Notification:
    needs: Code-checkout
    runs-on: self-hosted
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
          steps:  ${{toJson(steps)}}
          channel: '#android-app-notification'
          if: always()
        env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      
        
    
    
    
    
    
    
    # steps: 
    #    - name: Slack Notification
    #    # - uses: rtCamp/action-slack-notify@v2
    #      run: |
    #        curl -X POST -H 'Content-type: application/json' --data "{
    #        \"text\": \"${{ job.status }}\"
    #         }" https://hooks.slack.com/services/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

         
           
         # env: 
         #  SLACK_CHANNEL: android-app-notification
         #  SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         #  SLACK_ICON: https://github.com/rtCamp.png?size=48
         #  SLACK_MESSAGE: ${{ job.status }}
         #  SLACK_TITLE: Post Title
         #  SLACK_USERNAME: Cybage-SohamDemo
         #  SLACK_WEBHOOK: https://hooks.slack.com/services/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
