name: Android CI
on: 
  workflow_dispatch

jobs:
  Code-checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Lint-Report:
    runs-on: self-hosted
    steps:
    - name: Lint Report
      run: ./gradlew lintDebug
    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: app/build/reports/lint-results-debug.html
        if-no-files-found: warn
    
  Sonar-Analysis:
    runs-on: self-hosted
    steps:      
    - name: Sonar Analysis
      run: ./gradlew sonarqube

  Unit-Test: 
   runs-on: self-hosted
   steps:    
    - name: Unit Test Case
      run: ./gradlew test
    - name: Upload unit test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report.html
        path: app/build/reports/tests/testDebugUnitTest/index.html
        if-no-files-found: warn  
