name: Android CI
on: 
  workflow_dispatch

jobs:
  echo-job:
    runs-on: self-hosted

    steps:
    - name: Run Echo Command
      run: echo "Hello, GitHub Actions!"
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Lint Report
      run: ./gradlew lintDebug
    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: app/build/reports/lint-results-debug.html
        if-no-files-found: warn

      
    - name: Sonar Analysis
      run: ./gradlew sonarqube 
    - name: Unit Test Case
      run: ./gradlew test
