name: Android CI
on: 
  workflow_dispatch

jobs:
  echo-job:
    runs-on: self-hosted

    steps:
    - name: Run Echo Command
      run: echo "Hello, GitHub Actions!"
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Sonar Analysis
      run: ./gradlew sonarqube 
    - name: Unit Test Case
      run: ./gradlew test
